import { Router } from 'express';
import authRoutes from './auth';
import usersRoutes from './users';
import pacientesRoutes from './pacientes';
import prontuariosRoutes from './prontuarios';
import anamnesesRoutes from './anamneses';
import sessoesRoutes from './sessoes';
import laudosRoutes from './laudos';
import encaminhamentosRoutes from './encaminhamentos';
import comunicacaoRoutes from './comunicacao';
import financeiroRoutes from './financeiro';
import dashboardRoutes from './dashboard';
import responsaveisRoutes from './responsaveis';
import escolasRoutes from './escolas';
import documentosRoutes from './documentos';
import appointmentsRoutes from './appointments';
import libraryRoutes from './library';
import transactionsRoutes from './transactions';
import notificationsRoutes from './notifications';
import sessionRecordsRoutes from './session-records';
import protocolEvaluationsRoutes from './protocol-evaluations';
import interventionPlansRoutes from './intervention-plans';
import chatRoutes from './chat';
import availabilityRoutes from './availability';
import guardianRoutes from './guardian';
import uploadRoutes from './upload';
import sessionDiariesRoutes from './session-diaries';
import frequencySheetsRoutes from './frequency-sheets';
import interventionDocumentsRoutes from './intervention-documents';
import whatsappRoutes from './whatsapp';
import signatureRoutes from './signatures';
import abaProtocolsRoutes from './aba-protocols';
import evolutionComparisonRoutes from './evolution-comparison';
import consentsRoutes from './consents';
import permissionsRoutes from './permissions';
import nfseRoutes from './nfse';
import waitingRoomRoutes from './waiting-room';
import aiSuggestionsRoutes from './ai-suggestions';
import documentRequestsRoutes from './document-requests';
import billingRoutes from './billing';
import screeningsRoutes from './screenings';
import relatoriosRoutes from './relatorios';
import insightsRoutes from './insights';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', usersRoutes);
router.use('/pacientes', pacientesRoutes);
router.use('/prontuarios', prontuariosRoutes);
router.use('/anamneses', anamnesesRoutes);
router.use('/sessoes', sessoesRoutes);
router.use('/laudos', laudosRoutes);
router.use('/encaminhamentos', encaminhamentosRoutes);
router.use('/comunicacao', comunicacaoRoutes);
router.use('/financeiro', financeiroRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/responsaveis', responsaveisRoutes);
router.use('/escolas', escolasRoutes);
router.use('/documentos', documentosRoutes);
router.use('/appointments', appointmentsRoutes);
router.use('/library', libraryRoutes);
router.use('/transactions', transactionsRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/session-records', sessionRecordsRoutes);
router.use('/protocol-evaluations', protocolEvaluationsRoutes);
router.use('/intervention-plans', interventionPlansRoutes);
router.use('/chat', chatRoutes);
router.use('/guardian', guardianRoutes);
router.use('/upload', uploadRoutes);
router.use('/session-diaries', sessionDiariesRoutes);
router.use('/frequency-sheets', frequencySheetsRoutes);
router.use('/intervention-documents', interventionDocumentsRoutes);
router.use('/whatsapp', whatsappRoutes);
router.use('/signatures', signatureRoutes);
router.use('/aba', abaProtocolsRoutes);
router.use('/evolution', evolutionComparisonRoutes);
router.use('/consents', consentsRoutes);
router.use('/permissions', permissionsRoutes);
router.use('/nfse', nfseRoutes);
router.use('/waiting-room', waitingRoomRoutes);
router.use('/ai', aiSuggestionsRoutes);
router.use('/document-requests', documentRequestsRoutes);
router.use('/availability', availabilityRoutes);
router.use('/billing', billingRoutes);
router.use('/screenings', screeningsRoutes);
router.use('/relatorios', relatoriosRoutes);
router.use('/insights', insightsRoutes);

export default router;
