import { Component, AfterViewInit, OnDestroy } from '@angular/core';
import { RouterOutlet } from '@angular/router';

const ICON_LABELS: Record<string, string> = {
  // Navegação
  arrow_back: 'Voltar',
  arrow_forward: 'Avançar',
  chevron_left: 'Anterior',
  chevron_right: 'Próximo',
  close: 'Fechar',
  cancel: 'Cancelar',
  menu: 'Menu',
  home: 'Início',
  dashboard: 'Dashboard',
  settings: 'Configurações',
  logout: 'Sair',
  notifications: 'Notificações',
  notifications_none: 'Notificações',
  search: 'Buscar',
  search_off: 'Nenhum resultado',
  refresh: 'Atualizar',
  more_vert: 'Mais opções',
  open_in_new: 'Abrir em nova aba',
  link: 'Vincular',
  share: 'Compartilhar',
  download: 'Baixar',
  upload: 'Enviar',
  upload_file: 'Enviar arquivo',
  cloud_upload: 'Enviar',
  print: 'Imprimir',
  picture_as_pdf: 'Exportar PDF',
  save: 'Salvar',
  content_copy: 'Copiar',
  done_all: 'Concluído',
  check: 'Confirmar',
  check_circle: 'Concluído',
  verified: 'Verificado',
  error: 'Erro',
  warning: 'Atenção',
  info: 'Informação',

  // CRUD
  add: 'Adicionar',
  add_circle_outline: 'Adicionar',
  edit: 'Editar',
  edit_note: 'Editar',
  delete: 'Excluir',
  delete_outline: 'Excluir',
  visibility: 'Visualizar',
  preview: 'Visualizar',
  history: 'Histórico',
  archive: 'Arquivar',
  inbox: 'Caixa de entrada',
  folder_open: 'Abrir pasta',
  receipt: 'Recibo',
  receipt_long: 'Recibo',
  format_quote: 'Citação',
  sticky_note_2: 'Anotações',
  notes: 'Notas',
  description: 'Documento',
  assignment: 'Tarefa',
  playlist_add_check: 'Plano',
  summarize: 'Resumo',
  auto_awesome: 'IA',
  tips_and_updates: 'Dicas',
  insights: 'Insights',
  monitoring: 'Monitoramento',
  trending_up: 'Evolução',
  trending_down: 'Declínio',
  compare: 'Comparar',
  add_chart: 'Gráfico',
  pending: 'Pendente',
  hourglass_empty: 'Aguardando',
  event: 'Evento',
  event_note: 'Evento',
  event_busy: 'Ocupado',
  event_seat: 'Assento',
  calendar_today: 'Calendário',
  schedule: 'Horário',
  date_range: 'Período',
  access_time: 'Horário',
  alarm: 'Alarme',
  tv: 'Painel TV',
  play_arrow: 'Reproduzir',
  volume_up: 'Som',
  send: 'Enviar',
  chat: 'Chat',
  mail: 'Email',
  forward_to_inbox: 'Enviar',
  inbox_outlined: 'Caixa de entrada',
  flag: 'Objetivo',
  build: 'Habilidades',
  psychology: 'Psicopedagogia',
  science: 'Testes',
  draw: 'Desenhar',
  touch_app: 'Toque',
  menu_book: 'Livro',
  school: 'Escola',
  business: 'Empresa',
  location_on: 'Endereço',
  location_off: 'Sem endereço',
  location_city: 'Cidade',
  map: 'Mapa',
  markunread_mailbox: 'CEP',
  home_work: 'Endereço',
  door_front: 'Sala',

  // Pessoas
  person: 'Pessoa',
  person_add: 'Adicionar pessoa',
  people: 'Pessoas',
  group: 'Grupo',
  family_restroom: 'Família',
  badge: 'Crachá',
  tag: 'Tag',
  account_circle: 'Conta',
  face: 'Paciente',
  child_care: 'Criança',
  vpn_key: 'Chave de acesso',
  favorite: 'Favorito',
  star: 'Favorito',

  // Financeiro
  payments: 'Pagamentos',
  account_balance_wallet: 'Carteira',
  money: 'Valor',
  attach_money: 'Valor',
  credit_card: 'Cartão',
  receipt_long_outlined: 'Recibo',
  price_change: 'Preço',
  calculate: 'Cálculo',

  // Documentos
  picture_as_pdf_outlined: 'PDF',
  gpp_good: 'Proteção de dados',
  policy: 'Política',
  verified_user: 'Verificado',
  lock: 'Bloqueado',
  privacy_tip: 'Privacidade',
  doc: 'Documento',
  file_present: 'Arquivo',

  // Diversos
  camera_alt: 'Enviar foto',
  photo_camera: 'Enviar foto',
  image: 'Imagem',
  queue: 'Fila',
  play_arrow_outlined: 'Reproduzir',
  star_border: 'Favoritar',
  heart: 'Favorito',
  local_offer: 'Oferta',
  sell: 'Venda',
  shopping_cart: 'Carrinho',
  storefront: 'Loja',
  inventory: 'Estoque',
  warehouse: 'Depósito',
  login: 'Entrar',
  logout_outlined: 'Sair',
  help: 'Ajuda',
  help_outline: 'Ajuda',
  info_outline: 'Informação',
  question_answer: 'Perguntas',
  feedback: 'Feedback',
  report: 'Relatório',
  assignment_turned_in: 'Concluído',
  assignment_late: 'Atrasado',
  date_range_outlined: 'Período',
  weekend: 'Fim de semana',
  beach_access: 'Férias',
  wb_sunny: 'Sol',
  dark_mode: 'Modo escuro',
  light_mode: 'Modo claro',
  contrast: 'Tema',
  palette: 'Aparência',
  language: 'Idioma',
  translate: 'Tradução',
  font_download: 'Fonte',
  zoom_in: 'Ampliar',
  zoom_out: 'Reduzir',
  fullscreen: 'Tela cheia',
  fullscreen_exit: 'Sair da tela cheia',
  screen_share: 'Compartilhar tela',
  desktop_windows: 'Área de trabalho',
  smartphone: 'Celular',
  tablet: 'Tablet',
  laptop: 'Notebook',
  power_settings_new: 'Desligar',
  restart_alt: 'Reiniciar',
  sync: 'Sincronizar',
  sync_alt: 'Sincronizar',
  wifi: 'Wi-Fi',
  signal_cellular_alt: 'Sinal',
  battery_full: 'Bateria',
  network_check: 'Rede',
  security: 'Segurança',
  admin_panel_settings: 'Administração',
  manage_accounts: 'Gerenciar contas',
  supervisor_account: 'Supervisor',
  how_to_reg: 'Registro',
  how_to_vote: 'Votação',
  perm_identity: 'Identidade',
  contact_mail: 'Contato',
  contact_phone: 'Contato',
  email_outlined: 'Email',
  call: 'Telefone',
  phone: 'Telefone',
  phone_enabled: 'Telefone',
  message: 'Mensagem',
  sms: 'Mensagem',
  forum: 'Fórum',
  comment: 'Comentário',
  rate_review: 'Avaliar',
  reviews: 'Avaliações',
  thumb_up: 'Curtir',
  thumb_down: 'Não curtir',
  sentiment_satisfied: 'Satisfeito',
  sentiment_dissatisfied: 'Insatisfeito',
  sentiment_neutral: 'Neutro',
  emoji_emotions: 'Feliz',
  emoji_events: 'Premiação',
  emoji_objects: 'Objetivo',
  emoji_nature: 'Natureza',
  emoji_people: 'Pessoas',
  emoji_symbols: 'Símbolos',
  cake: 'Aniversário',
  celebration: 'Celebração',
  fitness_center: 'Atividade física',
  sports_soccer: 'Esporte',
  music_note: 'Música',
  theater_comedy: 'Teatro',
  movie: 'Filme',
  book: 'Livro',
  auto_stories: 'Leitura',
  school_outlined: 'Escola',
  class: 'Aula',
  group_work: 'Trabalho em grupo',
  diversity_3: 'Diversidade',
  public: 'Público',
  travel_explore: 'Explorar',
  explore: 'Explorar',
  place: 'Local',
  near_me: 'Próximo',
  navigation: 'Navegação',
  directions: 'Direções',
  flight: 'Voo',
  train: 'Trem',
  bus: 'Ônibus',
  directions_car: 'Carro',
  two_wheeler: 'Moto',
  local_taxi: 'Táxi',
  restaurant: 'Restaurante',
  local_cafe: 'Café',
  local_bar: 'Bar',
  local_grocery_store: 'Mercado',
  local_hospital: 'Hospital',
  local_pharmacy: 'Farmácia',
  local_hotel: 'Hotel',
  local_laundry_service: 'Lavanderia',
  local_mall: 'Shopping',
  local_parking: 'Estacionamento',
  local_play: 'Diversão',
  local_printshop: 'Gráfica',
  local_see: 'Câmera',
  local_shipping: 'Entrega',
  local_dining: 'Restaurante',
  room_service: 'Serviço de quarto',
  spa: 'Spa',
  pets: 'Animais',
  agriculture: 'Agricultura',
  forest: 'Floresta',
  park: 'Parque',
  camping: 'Acampamento',
  kitesurfing: 'Esporte',
  surfing: 'Surf',
  hiking: 'Trilha',
  snowboarding: 'Snowboard',
  skateboarding: 'Skate',
  cycling: 'Ciclismo',
  swimming: 'Natação',
  directions_run: 'Corrida',
  directions_walk: 'Caminhada',
  accessibility: 'Acessibilidade',
  accessible: 'Acessível',
  wheelchair_pickup: 'Cadeira de rodas',
  blind: 'Deficiência visual',
  hearing: 'Deficiência auditiva',
  sign_language: 'Libras',
  text_fields: 'Campos de texto',
  text_format: 'Formatação',
  format_bold: 'Negrito',
  format_italic: 'Itálico',
  format_underline: 'Sublinhado',
  format_list_bulleted: 'Lista',
  format_list_numbered: 'Lista numerada',
  format_align_left: 'Alinhar à esquerda',
  format_align_center: 'Centralizar',
  format_align_right: 'Alinhar à direita',
  format_align_justify: 'Justificar',
  format_clear: 'Limpar formatação',
  format_color_fill: 'Cor de preenchimento',
  format_color_text: 'Cor do texto',
  format_indent_decrease: 'Diminuir recuo',
  format_indent_increase: 'Aumentar recuo',
  format_line_spacing: 'Espaçamento',
  format_quote_outlined: 'Citação',
  format_shapes: 'Formas',
  format_size: 'Tamanho do texto',
  format_strikethrough: 'Riscado',
  format_underlined: 'Sublinhado',
  insert_chart: 'Inserir gráfico',
  insert_chart_outlined: 'Inserir gráfico',
  insert_comment: 'Inserir comentário',
  insert_drive_file: 'Inserir arquivo',
  insert_emoticon: 'Emoticon',
  insert_link: 'Inserir link',
  insert_photo: 'Inserir foto',
  insert_table: 'Inserir tabela',
  table_chart: 'Tabela',
  bar_chart: 'Gráfico de barras',
  pie_chart: 'Gráfico de pizza',
  donut_large: 'Gráfico de rosca',
  show_chart: 'Gráfico de linhas',
  scatter_plot: 'Gráfico de dispersão',
  bubble_chart: 'Gráfico de bolhas',
  timeline: 'Linha do tempo',
  view_agenda: 'Visão de agenda',
  view_carousel: 'Carrossel',
  view_column: 'Visão em colunas',
  view_day: 'Visão do dia',
  view_headline: 'Visão em linhas',
  view_list: 'Visão em lista',
  view_module: 'Visão em módulos',
  view_quilt: 'Visão em blocos',
  view_stream: 'Visão contínua',
  view_week: 'Visão da semana',
  view_array: 'Visão em faixas',
  view_sidebar: 'Visão lateral',
  apps: 'Aplicativos',
  widget: 'Widget',
  grid_view: 'Grade',
  list: 'Lista',
  reorder: 'Reordenar',
  drag_indicator: 'Arrastar',
  swap_vert: 'Ordenar',
  swap_horiz: 'Trocar',
  unfold_more: 'Expandir',
  unfold_less: 'Recolher',
  expand_more: 'Expandir',
  expand_less: 'Recolher',
  arrow_drop_down: 'Abrir',
  arrow_drop_up: 'Fechar',
  arrow_upward: 'Subir',
  arrow_downward: 'Descer',
  arrow_left: 'Esquerda',
  arrow_right: 'Direita',
  keyboard_arrow_up: 'Subir',
  keyboard_arrow_down: 'Descer',
  keyboard_arrow_left: 'Esquerda',
  keyboard_arrow_right: 'Direita',
  first_page: 'Primeira página',
  last_page: 'Última página',
  skip_next: 'Próximo',
  skip_previous: 'Anterior',
  fast_forward: 'Avançar rápido',
  fast_rewind: 'Retroceder',
  pause: 'Pausar',
  stop: 'Parar',
  replay: 'Repetir',
  loop: 'Repetir',
  shuffle: 'Aleatório',
  headphones: 'Fones',
  audiotrack: 'Áudio',
  video_library: 'Vídeos',
  video_call: 'Vídeo chamada',
  videocam: 'Câmera de vídeo',
  mic: 'Microfone',
  mic_off: 'Microfone desligado',
  record_voice_over: 'Gravação',
  keyboard_voice: 'Voz',
  surround_sound: 'Som',
  hd: 'Alta definição',
  subtitles: 'Legendas',
  closed_caption: 'Legendas',
  radio: 'Rádio',
  live_tv: 'TV ao vivo',
  movie_filter: 'Filtro de filme',
  grain: 'Textura',
  filter: 'Filtro',
  filter_alt: 'Filtrar',
  filter_list: 'Filtrar',
  sort: 'Ordenar',
  sort_by_alpha: 'Ordenar alfabeticamente',
  search_outlined: 'Buscar',
  find_in_page: 'Localizar',
  manage_search: 'Buscar',
  bookmarks: 'Favoritos',
  bookmark: 'Favorito',
  bookmark_border: 'Favoritar',
  star_rate: 'Favorito',
  grade: 'Avaliar',
  new_releases: 'Novidade',
  announcement: 'Anúncio',
  campaign: 'Campanha',
  celebration_outlined: 'Celebração',
  confetti: 'Confete',
  party_mode: 'Festa',
  sports_bar: 'Bar',
  sports_basketball: 'Basquete',
  sports_cricket: 'Críquete',
  sports_esports: 'Games',
  sports_golf: 'Golfe',
  sports_hockey: 'Hóquei',
  sports_mma: 'MMA',
  sports_motorsports: 'Motoresportes',
  sports_rugby: 'Rúgbi',
  sports_tennis: 'Tênis',
  sports_volleyball: 'Vôlei',
  sports: 'Esportes',
  fitness_center_outlined: 'Atividade física',
  self_improvement: 'Desenvolvimento',
  meditation: 'Meditação',
  mindfulness: 'Mindfulness',
  balance: 'Equilíbrio',
  workspace_premium: 'Premium',
  military_tech: 'Tecnologia militar',
  shield: 'Proteção',
  verified_outlined: 'Verificado',
  assignment_outlined: 'Tarefa',
  assignment_returned: 'Tarefa entregue',
  assignment_return: 'Devolver tarefa',
  assignment_turned_in_outlined: 'Concluído',
  check_circle_outline: 'Concluído',
  check_box: 'Selecionado',
  check_box_outline_blank: 'Selecionar',
  indeterminate_check_box: 'Seleção parcial',
  radio_button_checked: 'Selecionado',
  radio_button_unchecked: 'Selecionar',
  toggle_on: 'Ativado',
  toggle_off: 'Desativado',
  highlight_off: 'Remover',
  cancel_presentation: 'Cancelar',
  blocked: 'Bloqueado',
  do_not_disturb: 'Não perturbe',
  not_interested: 'Sem interesse',
  hourglass_top: 'Aguardando',
  hourglass_bottom: 'Quase pronto',
  timer: 'Temporizador',
  timer_off: 'Temporizador desligado',
  alarm_on: 'Alarme ativo',
  alarm_off: 'Alarme desligado',
  snooze: 'Adiar',
  more_time: 'Mais tempo',
  av_timer: 'Temporizador',
  update: 'Atualizar',
  pending_actions: 'Ações pendentes',
  schedule_send: 'Agendar envio',
  send_time_extension: 'Envio',
  published_with_changes: 'Publicado',
  unpublished: 'Não publicado',
  publish: 'Publicar',
  edit_calendar: 'Editar agenda',
  edit_off: 'Edição desativada',
  edit_outlined: 'Editar',
  edit_road: 'Editar',
  map_outlined: 'Mapa',
  alt_route: 'Rota alternativa',
  multiple_stop: 'Múltiplas paradas',
  transfer_within_a_station: 'Transferência',
  subway: 'Metrô',
  tram: 'Bonde',
  rail_alert: 'Trem',
  electric_car: 'Carro elétrico',
  car_repair: 'Oficina',
  gas_meter: 'Combustível',
  local_gas_station: 'Posto',
  local_airport: 'Aeroporto',
  local_atm: 'Caixa eletrônico',
  local_activity: 'Atividade',
  local_convenience_store: 'Conveniência',
  local_drink: 'Bebida',
  local_fire_department: 'Bombeiros',
  local_florist: 'Floricultura',
  local_library: 'Biblioteca',
  local_movies: 'Cinema',
  local_museum: 'Museu',
  local_offer_outlined: 'Oferta',
  local_police: 'Polícia',
  local_post_office: 'Correios',
  local_car_wash: 'Lava-rápido',
  local_moving: 'Mudança',
  local_shipping_outlined: 'Entrega',
  add_location: 'Adicionar local',
  add_location_alt: 'Adicionar local',
  add_road: 'Adicionar via',
  my_location: 'Minha localização',
  pin_drop: 'Pino',
  location_on_outlined: 'Localização',
  location_searching: 'Localizando',
  gps_fixed: 'GPS',
  gps_not_fixed: 'Sem GPS',
  gps_off: 'GPS desligado',
  not_listed_location: 'Local não listado',
  room: 'Sala',
  satellite: 'Satélite',
  streetview: 'Vista da rua',
  terrain: 'Terreno',
  traffic: 'Trânsito',
  transfer_within_a_station_outlined: 'Transferência',
  cleaning_services: 'Limpeza',
  construction: 'Construção',
  electrical_services: 'Elétrica',
  handyman: 'Manutenção',
  hardware: 'Ferramentas',
  plumbing: 'Hidráulica',
  roofing: 'Telhado',
  home_repair_service: 'Reparos',
  paint: 'Pintura',
  solar_power: 'Energia solar',
  wind_power: 'Energia eólica',
  water_drop: 'Água',
  waves: 'Ondas',
  opacit: 'Opacidade',
  opacity: 'Opacidade',
  brightness_high: 'Brilho alto',
  brightness_low: 'Brilho baixo',
  brightness_auto: 'Brilho automático',
  exposure: 'Exposição',
  flare: 'Flare',
  flash_auto: 'Flash automático',
  flash_off: 'Flash desligado',
  flash_on: 'Flash ligado',
  hdr_enhanced_select: 'HDR',
  hdr_off: 'HDR desligado',
  hdr_on: 'HDR ligado',
  lens: 'Lente',
  motion_photos_off: 'Fotos em movimento',
  motion_photos_on: 'Fotos em movimento',
  photo: 'Foto',
  photo_album: 'Álbum',
  photo_library: 'Biblioteca de fotos',
  photo_size_select_large: 'Foto grande',
  photo_size_select_small: 'Foto pequena',
  photos: 'Fotos',
  add_a_photo: 'Adicionar foto',
  add_photo_alternate: 'Adicionar foto',
  collections: 'Coleção',
  collections_bookmark: 'Coleção',
  control_camera: 'Controlar câmera',
  crop: 'Recortar',
  crop_free: 'Recorte livre',
  crop_landscape: 'Recortar paisagem',
  crop_portrait: 'Recortar retrato',
  crop_rotate: 'Rotacionar recorte',
  crop_square: 'Recortar quadrado',
  flip: 'Inverter',
  rotate_90_degrees_ccw: 'Rotacionar',
  rotate_left: 'Rotacionar à esquerda',
  rotate_right: 'Rotacionar à direita',
  straighten: 'Endireitar',
  wb_auto: 'Balanço automático',
  wb_cloudy: 'Nublado',
  wb_incandescent: 'Lâmpada',
  wb_iridescent: 'Brilho',
  wb_shade: 'Sombra',
  wb_twilight: 'Crepúsculo',
  brightness_1: 'Brilho 1',
  brightness_2: 'Brilho 2',
  brightness_3: 'Brilho 3',
  brightness_4: 'Brilho 4',
  brightness_5: 'Brilho 5',
  brightness_6: 'Brilho 6',
  brightness_7: 'Brilho 7',
  contrast_outlined: 'Contraste',
  invert_colors: 'Inverter cores',
  invert_colors_off: 'Cores normais',
  panorama: 'Panorama',
  panorama_fish_eye: 'Panorama 360',
  panorama_horizontal: 'Panorama horizontal',
  panorama_vertical: 'Panorama vertical',
  blur_circular: 'Desfoque',
  blur_linear: 'Desfoque linear',
  blur_off: 'Sem desfoque',
  blur_on: 'Desfoque',
  dehaze: 'Desfocar',
  grain_outlined: 'Textura',
  grid_on: 'Grade',
  grid_off: 'Sem grade',
  image_aspect_ratio: 'Proporção',
  image_not_supported: 'Sem imagem',
  image_search: 'Buscar imagem',
  contrast_circle: 'Contraste',
  video_settings: 'Config. de vídeo',
  play_circle: 'Reproduzir',
  play_circle_filled: 'Reproduzir',
  play_circle_outline: 'Reproduzir',
  replay_circle_filled: 'Repetir',
  add_to_queue: 'Adicionar à fila',
  playlist_add: 'Adicionar à lista',
  playlist_add_check_outlined: 'Adicionar à lista',
  playlist_play: 'Lista de reprodução',
  queue_music: 'Fila de músicas',
  queue_play_next: 'Próximo na fila',
  featured_play_list: 'Lista em destaque',
  featured_video: 'Vídeo em destaque',
  fiber_dvr: 'DVR',
  fiber_manual_record: 'Gravação',
  fiber_new: 'Novo',
  fiber_pin: 'Fixo',
  fiber_smart_record: 'Gravação',
  control_point: 'Adicionar',
  control_point_duplicate: 'Duplicar',
  add_box: 'Adicionar',
  add_circle: 'Adicionar',
  add_circle_outline_outlined: 'Adicionar',
  library_add: 'Adicionar à biblioteca',
  library_add_check: 'Adicionado',
  library_books: 'Biblioteca',
  library_music: 'Biblioteca de músicas',
  library_music_outlined: 'Biblioteca',
  nightlight: 'Modo escuro',
  nightlight_round: 'Modo escuro',
  bedtime: 'Hora de dormir',
  bedtime_off: 'Hora de acordar',
  mode_night: 'Modo noturno',
  wb_sunny_outlined: 'Sol',
  sunny: 'Sol',
  thunderstorm: 'Tempestade',
  rainy: 'Chuva',
  snowy: 'Neve',
  foggy: 'Neblina',
  cloudy: 'Nublado',
  partly_cloudy_day: 'Parcialmente nublado',
  partly_cloudy_night: 'Parcialmente nublado',
  clear_day: 'Dia limpo',
  clear_night: 'Noite limpa',
  air: 'Ar',
  water: 'Água',
  dew_point: 'Ponto de orvalho',
  humidity_low: 'Umidade baixa',
  humidity_high: 'Umidade alta',
  humidity_mid: 'Umidade média',
  tornado: 'Tornado',
  tsunami: 'Tsunami',
  volcano: 'Vulcão',
  earthquake: 'Terremoto',
  flood: 'Enchente',
  wildfire: 'Incêndio',
  drought: 'Seca',
  snowing: 'Nevando',
  sunny_snowing: 'Sol com neve',
  rain_light: 'Chuva leve',
  rain_heavy: 'Chuva forte',
  snow_heavy: 'Neve forte',
  snowing_heavy: 'Nevando forte',
  icicles: 'Gelo',
  storm: 'Tempestade',
  hail: 'Granizo',
  mist: 'Névoa',
  smoke: 'Fumaça',
  dust: 'Poeira',
  sandstorm: 'Tempestade de areia',
  wind: 'Vento',
  broccolli: 'Brócolis',
  broccoli: 'Brócolis',
  egg: 'Ovo',
  egg_alt: 'Ovo',
  bacon: 'Bacon',
  bistro_table: 'Mesa',
  brunch_dining: 'Brunch',
  cake_outlined: 'Bolo',
  cheese: 'Queijo',
  checkout: 'Finalizar',
  cookies: 'Biscoitos',
  cooking: 'Cozinhando',
  countertops: 'Bancada',
  course: 'Curso',
  design_services: 'Design',
  dinner_dining: 'Jantar',
  dishwasher: 'Lava-louças',
  dry: 'Limpeza a seco',
  dry_cleaning: 'Lavanderia',
  food_bank: 'Banco de alimentos',
  free_breakfast: 'Café da manhã',
  golf_course: 'Campo de golfe',
  grass: 'Grama',
  grocery: 'Mercado',
  grocery_outlined: 'Mercado',
  group_off: 'Sem grupo',
  group_remove: 'Remover do grupo',
  groups: 'Grupos',
  groups_2: 'Grupos',
  groups_3: 'Grupos',
  handshake: 'Aperto de mãos',
  health_and_safety: 'Saúde e segurança',
  healthcare: 'Saúde',
  heart_broken: 'Coração partido',
  heart_outlined: 'Favorito',
  height: 'Altura',
  high_quality: 'Alta qualidade',
  highlight: 'Destacar',
  highlight_alt: 'Destacar',
  history_edu: 'História',
  home_outlined: 'Início',
  hot_tub: 'Ofurô',
  icecream: 'Sorvete',
  image_outlined: 'Imagem',
  imagesearch_roller: 'Pesquisar imagem',
  kebab_dining: 'Kebab',
  keyboard: 'Teclado',
  keyboard_alt: 'Teclado',
  keyboard_backspace: 'Voltar',
  keyboard_capslock: 'Caps lock',
  keyboard_command_key: 'Comando',
  keyboard_control_key: 'Controle',
  keyboard_double_arrow_down: 'Descer',
  keyboard_double_arrow_left: 'Esquerda',
  keyboard_double_arrow_right: 'Direita',
  keyboard_double_arrow_up: 'Subir',
  keyboard_arrow_back: 'Voltar',
  keyboard_hide: 'Ocultar teclado',
  keyboard_option_key: 'Opção',
  keyboard_return: 'Retorno',
  keyboard_tab: 'Tab',
  keyboard_voice_outlined: 'Voz',
  king_bed: 'Cama',
  kitchen: 'Cozinha',
  laundry: 'Lavanderia',
  lawn: 'Gramado',
  lighting: 'Iluminação',
  liquidation: 'Liquidação',
  livestream: 'Transmissão ao vivo',
  luggage: 'Bagagem',
  lunch_dining: 'Almoço',
  macro_off: 'Macro desligado',
  macro_on: 'Macro ligado',
  male: 'Masculino',
  female: 'Feminino',
  transgender: 'Transgênero',
  man: 'Homem',
  woman: 'Mulher',
  boy: 'Menino',
  girl: 'Menina',
  baby_changing_station: 'Fraldário',
  crib: 'Berço',
  stroller: 'Carrinho',
  escalator: 'Escada rolante',
  elevator: 'Elevador',
  chair: 'Cadeira',
  chair_alt: 'Cadeira',
  coffee: 'Café',
  coffee_maker: 'Cafeteira',
  connected_tv: 'TV conectada',
  controller_gen: 'Controle',
  density_large: 'Densidade',
  density_medium: 'Densidade média',
  density_small: 'Densidade baixa',
  desktop_access_disabled: 'Sem acesso',
  developer_board: 'Placa',
  devices: 'Dispositivos',
  devices_other: 'Outros dispositivos',
  dialpad: 'Teclado numérico',
  dining: 'Jantar',
  dinner_dining_outlined: 'Jantar',
  disabled_by_default: 'Desabilitado',
  do_not_step: 'Não pisar',
  do_not_touch: 'Não tocar',
  door_sliding: 'Porta',
  dns: 'DNS',
  domain: 'Domínio',
  domain_disabled: 'Domínio desabilitado',
  domain_verification: 'Verificação de domínio',
  duplex: 'Duplex',
  east: 'Leste',
  edit_attributes: 'Editar atributos',
  eduroam: 'Rede',
  electric_bike: 'Bicicleta elétrica',
  electric_moped: 'Moto elétrica',
  electric_rickshaw: 'Riquixá',
  electric_scooter: 'Patinete',
  electrical_services_outlined: 'Elétrica',
  emergency: 'Emergência',
  emergency_recording: 'Gravação de emergência',
  emergency_share: 'Compartilhar emergência',
  emoji_food_beverage: 'Comida',
  emoji_nature_outlined: 'Natureza',
  emoji_objects_outlined: 'Objetos',
  emoji_people_outlined: 'Pessoas',
  emoji_symbols_outlined: 'Símbolos',
  emoji_transportation: 'Transporte',
  energy_savings_leaf: 'Economia',
  engineering: 'Engenharia',
  enhanced_encryption: 'Criptografia',
  ent: 'ENT',
  enterprise: 'Empresa',
  enterprise_off: 'Sem empresa',
  equalizer: 'Equalizador',
  eraser_size_1: 'Borracha',
  eraser_size_2: 'Borracha',
  eraser_size_3: 'Borracha',
  error_outline: 'Erro',
  error_rounded: 'Erro',
  escalator_warning: 'Escada rolante',
  event_available: 'Disponível',
  event_repeat: 'Repetir evento',
  event_upcoming: 'Próximo evento',
  events: 'Eventos',
  fact_check: 'Verificação',
  family_history: 'Histórico familiar',
  fastfood: 'Fast food',
  faucet: 'Torneira',
  featured_seasonal_and_gifts: 'Presentes',
  file_copy: 'Copiar arquivo',
  file_download: 'Baixar arquivo',
  file_download_done: 'Download concluído',
  file_download_off: 'Download desativado',
  file_open: 'Abrir arquivo',
  file_upload: 'Enviar arquivo',
  filter_1: 'Filtro 1',
  filter_2: 'Filtro 2',
  filter_3: 'Filtro 3',
  filter_4: 'Filtro 4',
  filter_5: 'Filtro 5',
  filter_6: 'Filtro 6',
  filter_7: 'Filtro 7',
  filter_8: 'Filtro 8',
  filter_9: 'Filtro 9',
  filter_9_plus: 'Filtro 9+',
  filter_alt_off: 'Sem filtro',
  filter_alt_outlined: 'Filtrar',
  filter_b_and_w: 'Preto e branco',
  filter_center_focus: 'Centralizar',
  filter_drama: 'Drama',
  filter_frames: 'Moldura',
  filter_hdr: 'HDR',
  filter_list_alt: 'Filtrar',
  filter_none: 'Sem filtro',
  filter_tilt_shift: 'Inclinar',
  filter_vintage: 'Vintage',
  fireplace: 'Lareira',
  fire_hydrant: 'Hidrante',
  fit_screen: 'Ajustar tela',
  flatware: 'Talheres',
  flight_class: 'Classe de voo',
  flight_land: 'Pouso',
  flight_takeoff: 'Decolagem',
  flightsmode: 'Modo voo',
  fluid: 'Fluido',
  fluid_balance: 'Equilíbrio',
  fluid_med: 'Medicamento',
  fluid_med_outlined: 'Medicamento',
  fmd_bad: 'Local ruim',
  fmd_good: 'Local bom',
  food_bank_outlined: 'Banco de alimentos',
  foundation: 'Fundação',
  frame_person: 'Pessoa',
  frame_source: 'Fonte',
  frames: 'Moldura',
  functions: 'Funções',
  gamepad: 'Controle',
  games: 'Jogos',
  garage: 'Garagem',
  garbage: 'Lixo',
  garden_cart: 'Carrinho de jardim',
  gesture: 'Gesto',
  get_app: 'Baixar',
  gif: 'GIF',
  gif_box: 'GIF',
  glass_cup: 'Copo',
  gluten_free: 'Sem glúten',
  gpp_bad: 'Proteção ruim',
  gpp_good_outlined: 'Proteção',
  gpp_maybe: 'Proteção incerta',
  gps_fixed_outlined: 'GPS',
  graphic_eq: 'Equalizador',
  grid_3x3: 'Grade 3x3',
  grid_3x3_off: 'Grade 3x3 desligada',
  grid_4x4: 'Grade 4x4',
  grid_goldenratio: 'Grade dourada',
  grid_guides: 'Guias',
  grid_view_outlined: 'Grade',
  group_add: 'Adicionar grupo',
  group_off_outlined: 'Sem grupo',
  group_outlined: 'Grupo',
  groups_outlined: 'Grupos',
  hand_bones: 'Mão',
  hand_gesture: 'Gesto',
  hard_drive: 'Disco rígido',
  hard_drive_2: 'Disco rígido',
  hardware_outlined: 'Hardware',
  home_improvement_and_lawn: 'Melhorias',
  home_max: 'Casa',
  home_mini: 'Casa',
  home_pin: 'Casa',
  home_repair_service_outlined: 'Reparos',
  home_work_outlined: 'Trabalho',
  horizontal_distribute: 'Distribuir',
  horizontal_rule: 'Linha horizontal',
  horizontal_split: 'Dividir',
  hot_tub_outlined: 'Ofurô',
  hotel: 'Hotel',
  hotel_class: 'Classe',
  hourglass_bottom_outlined: 'Quase pronto',
  hourglass_disabled: 'Tempo esgotado',
  hourglass_empty_outlined: 'Aguardando',
  hourglass_full: 'Tempo completo',
  hourglass_top_outlined: 'Aguardando',
  house: 'Casa',
  house_outlined: 'Casa',
  house_siding: 'Revestimento',
  houseboat: 'Casa flutuante',
  humidity_percentage: 'Umidade',
  hvac: 'Ar-condicionado',
  ice_skating: 'Patinar',
  image_aspect_ratio_outlined: 'Proporção',
  image_not_supported_outlined: 'Sem imagem',
  imagesearch_roller_outlined: 'Pesquisar imagem',
  import_contacts: 'Importar contatos',
  import_export: 'Importar/Exportar',
  important_devices: 'Dispositivos',
  in_home_mode: 'Em casa',
  indentation: 'Recuo',
  incident: 'Incidente',
  indoor_grass: 'Grama',
  insert_comment_outlined: 'Comentário',
  insert_drive_file_outlined: 'Arquivo',
  insert_emoticon_outlined: 'Emoticon',
  insert_link_outlined: 'Link',
  insert_page_break: 'Quebra de página',
  insert_photo_outlined: 'Foto',
  interactive_space: 'Espaço',
  intercom: 'Interfone',
  interest: 'Interesse',
  inventory_2: 'Estoque',
  invert_colors_outlined: 'Cores',
  ios_share: 'Compartilhar iOS',
  join_full: 'Participar',
  join_inner: 'Participar',
  join_left: 'Participar',
  join_right: 'Participar',
  kayaking: 'Caiaque',
  keyboard_outlined: 'Teclado',
  kitchen_outlined: 'Cozinha',
  kitesurfing_outlined: 'Kitesurf',
  label: 'Rótulo',
  label_important: 'Rótulo importante',
  label_off: 'Sem rótulo',
  labels: 'Rótulos',
  landline: 'Telefone fixo',
  landscape: 'Paisagem',
  layers: 'Camadas',
  layers_clear: 'Limpar camadas',
  leaderboard: 'Ranking',
  leak_add: 'Vazar',
  leak_remove: 'Remover vazamento',
  learning: 'Aprendizado',
  lens_blur: 'Desfoque',
  lens_outlined: 'Lente',
  letter_space: 'Espaço de letras',
  library_add_outlined: 'Biblioteca',
  light: 'Luz',
  lightbulb: 'Ideia',
  lightbulb_outline: 'Ideia',
  light_outlined: 'Luz',
  lightning_stand: 'Raio',
  line_axis: 'Linha',
  line_style: 'Estilo de linha',
  line_weight: 'Peso da linha',
  linear_scale: 'Escala',
  linked_camera: 'Câmera conectada',
  list_alt: 'Lista',
  list_alt_outlined: 'Lista',
  live_help: 'Ajuda ao vivo',
  living: 'Sala de estar',
  local_activity_outlined: 'Atividade',
  local_fire_department_outlined: 'Bombeiros',
  local_florist_outlined: 'Floricultura',
  local_hospital_outlined: 'Hospital',
  local_library_outlined: 'Biblioteca',
  local_see_outlined: 'Câmera',
  location_away: 'Local distante',
  location_home: 'Local de casa',
  location_pin: 'Local',
  lock_clock: 'Bloqueado com horário',
  lock_open: 'Desbloqueado',
  lock_outline: 'Bloqueado',
  login_outlined: 'Entrar',
  looks: 'Aparência',
  looks_3: 'Aparência 3',
  looks_4: 'Aparência 4',
  looks_5: 'Aparência 5',
  looks_6: 'Aparência 6',
  looks_one: 'Aparência 1',
  looks_two: 'Aparência 2',
  loupe: 'Lupa',
  low_density: 'Baixa densidade',
  low_priority: 'Baixa prioridade',
  lowercase: 'Minúsculas',
  loyalty: 'Fidelidade',
  lte_mobiledata: 'LTE',
  lte_plus_mobiledata: 'LTE+',
  luggage_outlined: 'Bagagem',
  lunch_dining_outlined: 'Almoço',
  mail_lock: 'Email seguro',
  mail_outline: 'Email',
  maps_ugc: 'Mapas',
  mark_as_unread: 'Marcar como não lido',
  mark_chat_read: 'Marcar como lido',
  mark_chat_unread: 'Marcar como não lido',
  mark_email_read: 'Email lido',
  mark_email_unread: 'Email não lido',
  markunread: 'Não lido',
  markunread_mailbox_outlined: 'Caixa de correio',
  mask: 'Máscara',
  masks: 'Máscaras',
  maximize: 'Maximizar',
  media_bluetooth_off: 'Bluetooth off',
  media_bluetooth_on: 'Bluetooth',
  mediation: 'Mediação',
  medical_information: 'Informação médica',
  medical_services: 'Serviços médicos',
  medication: 'Medicação',
  medication_liquid: 'Medicação líquida',
  meeting_room: 'Sala de reunião',
  memory: 'Memória',
  menstrual: 'Menstrual',
  merge: 'Mesclar',
  merge_type: 'Tipo de mesclagem',
  mic_external_off: 'Microfone off',
  mic_external_on: 'Microfone',
  microwave: 'Micro-ondas',
  military_tech_outlined: 'Tecnologia',
  minimize: 'Minimizar',
  missed_video_call: 'Chamada perdida',
  mms: 'MMS',
  mobile_friendly: 'Compatível',
  mobile_off: 'Celular desligado',
  mobile_screen_share: 'Compartilhar tela',
  mobiledata_off: 'Dados móveis off',
  mode: 'Modo',
  mode_comment: 'Comentário',
  mode_edit: 'Editar',
  mode_edit_outline: 'Editar',
  mode_fan_off: 'Ventilador off',
  mode_fan_on: 'Ventilador',
  mode_heat_cool: 'Aquecimento',
  mode_heat_off: 'Aquecimento off',
  mode_heat_on: 'Aquecimento',
  model_training: 'Treinamento',
  monetization_on: 'Monetização',
  money_off: 'Sem dinheiro',
  money_off_csred: 'Sem dinheiro',
  monitor: 'Monitor',
  monitor_heart: 'Monitor cardíaco',
  monitor_weight: 'Peso',
  monochrome_photos: 'Fotos monocromáticas',
  mood: 'Humor',
  mood_bad: 'Mau humor',
  moped: 'Moto',
  more: 'Mais',
  more_horiz: 'Mais opções',
  more_vert_outlined: 'Mais opções',
  mortar: 'Argamassa',
  mosque: 'Mesquita',
  motion_photos_auto: 'Fotos automáticas',
  motion_photos_pause: 'Pausar fotos',
  motion_photos_paused: 'Fotos pausadas',
  move: 'Mover',
  move_down: 'Mover para baixo',
  move_to_inbox: 'Mover para caixa',
  move_up: 'Mover para cima',
  movie_creation: 'Criação de filme',
  movie_filter_outlined: 'Filtro de filme',
  moving: 'Mudança',
  mp: 'MP',
  multid_stop: 'Multi-stop',
  multiply: 'Multiplicar',
  museum: 'Museu',
  music_note_outlined: 'Música',
  music_off: 'Música off',
  music_video: 'Vídeo musical',
  my_location_outlined: 'Minha localização',
  nat: 'NAT',
  nature: 'Natureza',
  nature_people: 'Natureza e pessoas',
  navigate_before: 'Anterior',
  navigate_next: 'Próximo',
  near_me_disabled: 'Próximo desabilitado',
  near_me_outlined: 'Próximo',
  nearby_error: 'Erro próximo',
  nearby_off: 'Desligado',
  network_cell: 'Rede celular',
  network_locked: 'Rede bloqueada',
  network_ping: 'Ping',
  network_wifi: 'Rede Wi-Fi',
  network_wifi_1_bar: 'Wi-Fi fraco',
  network_wifi_2_bar: 'Wi-Fi médio',
  network_wifi_3_bar: 'Wi-Fi bom',
  new_label: 'Novo rótulo',
  next_plan: 'Próximo plano',
  next_week: 'Próxima semana',
  night_shelter: 'Abrigo',
  nightlife: 'Vida noturna',
  nightlight_outlined: 'Modo escuro',
  no_backpack: 'Sem mochila',
  no_drinks: 'Sem bebidas',
  no_encryption: 'Sem criptografia',
  no_encryption_gmailerrorred: 'Sem criptografia',
  no_flash: 'Sem flash',
  no_food: 'Sem comida',
  no_luggage: 'Sem bagagem',
  no_meals: 'Sem refeições',
  no_meeting_room: 'Sem sala',
  no_photography: 'Sem fotografia',
  no_sim: 'Sem SIM',
  no_stroller: 'Sem carrinho',
  no_transfer: 'Sem transferência',
  noise_aware: 'Ruído',
  noise_control_off: 'Controle de ruído',
  nordic_walking: 'Caminhada nórdica',
  north: 'Norte',
  north_east: 'Nordeste',
  north_west: 'Noroeste',
  not_accessible: 'Não acessível',
  not_accessible_forward: 'Não acessível',
  not_started: 'Não iniciado',
  note: 'Nota',
  note_add: 'Adicionar nota',
  note_alt: 'Nota',
  notes_outlined: 'Notas',
  notification_add: 'Adicionar notificação',
  notification_important: 'Notificação importante',
  notifications_active: 'Notificações ativas',
  notifications_off: 'Notificações desligadas',
  notifications_paused: 'Notificações pausadas',
  notifications_outlined: 'Notificações',
  numbers: 'Números',
  offline_bolt: 'Relâmpago offline',
  offline_pin: 'Pino offline',
  offline_share: 'Compartilhar offline',
  oil_barrel: 'Barril de óleo',
  on_device_training: 'Treinamento no dispositivo',
  ondemand_video: 'Vídeo sob demanda',
  online_prediction: 'Previsão online',
  opacity_outlined: 'Opacidade',
  open_in_full: 'Abrir em tela cheia',
  open_with: 'Abrir com',
  other_houses: 'Outras casas',
  outbound: 'Saída',
  outbox: 'Caixa de saída',
  outdoor_grill: 'Churrasqueira',
  output: 'Saída',
  padding: 'Preenchimento',
  pages: 'Páginas',
  pageview: 'Visualização',
  paid: 'Pago',
  palette_outlined: 'Paleta',
  pan_tool: 'Ferramenta de pan',
  pan_tool_alt: 'Ferramenta de pan',
  panorama_photosphere: 'Panorama',
  panorama_photosphere_select: 'Panorama',
  parachute: 'Paraquedas',
  park_outlined: 'Parque',
  pause_circle: 'Pausar',
  pause_circle_filled: 'Pausar',
  pause_circle_outline: 'Pausar',
  pause_presentation: 'Pausar apresentação',
  payment: 'Pagamento',
  payments_outlined: 'Pagamentos',
  pedal_bike: 'Bicicleta',
  pending_outlined: 'Pendente',
  people_alt: 'Pessoas',
  people_alt_outlined: 'Pessoas',
  people_outline: 'Pessoas',
  perm_camera_mic: 'Câmera e microfone',
  perm_contact_calendar: 'Contato e calendário',
  perm_data_setting: 'Dados',
  perm_media: 'Mídia',
  perm_phone_msg: 'Mensagem de voz',
  perm_scan_wifi: 'Wi-Fi',
  person_2: 'Pessoa 2',
  person_3: 'Pessoa 3',
  person_4: 'Pessoa 4',
  person_add_alt: 'Adicionar pessoa',
  person_add_alt_1: 'Adicionar pessoa',
  person_add_disabled: 'Adicionar desabilitado',
  person_add_outlined: 'Adicionar pessoa',
  person_off: 'Pessoa desabilitada',
  person_outline: 'Pessoa',
  person_pin: 'Pessoa fixada',
  person_pin_circle: 'Pessoa no local',
  person_remove: 'Remover pessoa',
  person_remove_alt_1: 'Remover pessoa',
  person_search: 'Buscar pessoa',
  personal_video: 'Vídeo pessoal',
  pest_control: 'Controle de pragas',
  pest_control_rodent: 'Controle de roedores',
  pets_outlined: 'Animais',
  pharmacy: 'Farmácia',
  phone_android: 'Telefone Android',
  phone_bluetooth_speaker: 'Telefone Bluetooth',
  phone_callback: 'Retorno de chamada',
  phone_disabled: 'Telefone desabilitado',
  phone_enabled_outlined: 'Telefone',
  phone_forwarded: 'Chamada encaminhada',
  phone_in_talk: 'Em chamada',
  phone_iphone: 'Telefone iPhone',
  phone_locked: 'Telefone bloqueado',
  phone_missed: 'Chamada perdida',
  phone_paused: 'Chamada pausada',
  phonelink: 'Link de telefone',
  phonelink_erase: 'Apagar link',
  phonelink_lock: 'Bloquear link',
  phonelink_off: 'Link desligado',
  phonelink_ring: 'Link de toque',
  phonelink_setup: 'Configurar link',
  photo_album_outlined: 'Álbum',
  photo_camera_back: 'Câmera traseira',
  photo_camera_front: 'Câmera frontal',
  photo_filter: 'Filtro de foto',
  photo_library_outlined: 'Biblioteca de fotos',
  photo_size_select_actual: 'Tamanho real',
  photo_size_select_large_outlined: 'Foto grande',
  photofilter: 'Filtro de foto',
  pin: 'Fixar',
  pin_end: 'Fim do pin',
  pin_invoke: 'Invocar pin',
  pinch: 'Pinça',
  pin_drop_outlined: 'Pino',
  pix: 'Pix',
  plague: 'Praga',
  planner_restart: 'Planejador',
  play_disabled: 'Reprodução desabilitada',
  play_for_work: 'Reproduzir',
  play_lesson: 'Aula',
  play_shape: 'Forma de reprodução',
  podcast: 'Podcast',
  point_of_sale: 'PDV',
  policy_outlined: 'Política',
  polygon: 'Polígono',
  portable_wifi_off: 'Wi-Fi portátil off',
  potted_plant: 'Planta',
  power: 'Energia',
  power_input: 'Entrada de energia',
  power_off: 'Energia off',
  precision_manufacturing: 'Precisão',
  pregnancy: 'Gravidez',
  present_to_all: 'Apresentar',
  preview_outlined: 'Visualizar',
  price_change_outlined: 'Preço',
  price_check: 'Verificar preço',
  print_disabled: 'Impressão desabilitada',
  print_outlined: 'Imprimir',
  process_chart: 'Gráfico de processo',
  production_quantity_limits: 'Limites',
  prop: 'Apoio',
  punch_clock: 'Relógio de ponto',
  push_pin: 'Pino',
  qr_code: 'QR Code',
  qr_code_2: 'QR Code',
  qr_code_scanner: 'Leitor de QR',
  query_stats: 'Estatísticas',
  question_mark: 'Ponto de interrogação',
  quickreply: 'Resposta rápida',
  quiz: 'Quiz',
  radar: 'Radar',
  radio_button_checked_outlined: 'Selecionado',
  radio_button_unchecked_outlined: 'Selecionar',
  ramen_dining: 'Ramen',
  ramp_left: 'Rampa esquerda',
  ramp_right: 'Rampa direita',
  rate_review_outlined: 'Avaliar',
  raw_off: 'Raw off',
  raw_on: 'Raw',
  read_more: 'Ler mais',
  real_estate_agent: 'Imóvel',
  recommended: 'Recomendado',
  record_voice_over_outlined: 'Gravação',
  redeem: 'Resgatar',
  reduce_capacity: 'Reduzir capacidade',
  remember_me: 'Lembrar de mim',
  remove: 'Remover',
  remove_circle: 'Remover',
  remove_circle_outline: 'Remover',
  remove_done: 'Remover concluído',
  remove_from_queue: 'Remover da fila',
  remove_moderator: 'Remover moderador',
  remove_red_eye: 'Visualizar',
  remove_road: 'Remover via',
  remove_shopping_cart: 'Remover do carrinho',
  reopen_window: 'Reabrir janela',
  replay_10: 'Repetir 10s',
  replay_30: 'Repetir 30s',
  replay_5: 'Repetir 5s',
  reply: 'Responder',
  reply_all: 'Responder a todos',
  report_gmailerrorred: 'Relatório',
  report_off: 'Sem relatório',
  report_outlined: 'Relatório',
  request_page: 'Solicitar página',
  request_quote: 'Solicitar cotação',
  reset_tv: 'Resetar TV',
  restart_alt_outlined: 'Reiniciar',
  restore: 'Restaurar',
  restore_from_trash: 'Restaurar da lixeira',
  restore_page: 'Restaurar página',
  rice_bowl: 'Tigela de arroz',
  ring_volume: 'Toque',
  rocket: 'Foguete',
  rocket_launch: 'Lançamento',
  rollup: 'Agrupar',
  rooftop: 'Telhado',
  room_preferences: 'Preferências da sala',
  room_service_outlined: 'Serviço de quarto',
  rotate_90_degrees_cw: 'Rotacionar',
  rotate_left_outlined: 'Rotacionar à esquerda',
  rotate_right_outlined: 'Rotacionar à direita',
  roundabout_left: 'Rotatória',
  roundabout_right: 'Rotatória',
  route: 'Rota',
  router: 'Roteador',
  rss_feed: 'RSS',
  rsvp: 'RSVP',
  ruler: 'Régua',
  run_circle: 'Correr',
  safari: 'Safari',
  safety_check: 'Verificação de segurança',
  safety_divider: 'Divisor',
  sailing: 'Vela',
  sanitizer: 'Desinfetante',
  save_alt: 'Salvar',
  saved_search: 'Busca salva',
  savings: 'Economia',
  scanner: 'Scanner',
  screen_lock_landscape: 'Bloqueio de tela',
  screen_lock_portrait: 'Bloqueio de tela',
  screen_lock_rotation: 'Bloqueio de rotação',
  screen_rotation: 'Rotação de tela',
  screen_rotation_alt: 'Rotação de tela',
  screen_search_desktop: 'Busca na área de trabalho',
  screenshot: 'Captura de tela',
  sd: 'SD',
  sd_card: 'Cartão SD',
  sd_card_alert: 'Cartão SD',
  sd_storage: 'Armazenamento',
  search_off_outlined: 'Nenhum resultado',
  security_update: 'Atualização de segurança',
  security_update_good: 'Atualização',
  security_update_warning: 'Atualização',
  segment: 'Segmento',
  select_all: 'Selecionar tudo',
  sell_outlined: 'Venda',
  send_and_archive: 'Enviar e arquivar',
  send_outlined: 'Enviar',
  sensor_door: 'Sensor de porta',
  sensor_occupied: 'Sensor de presença',
  sensor_window: 'Sensor de janela',
  sensors: 'Sensores',
  sensors_off: 'Sensores off',
  sentiment_calm: 'Calmo',
  sentiment_content: 'Contente',
  sentiment_excited: 'Empolgado',
  sentiment_frustrated: 'Frustrado',
  sentiment_neutral_outlined: 'Neutro',
  sentiment_sad: 'Triste',
  sentiment_stressed: 'Estressado',
  sentiment_very_dissatisfied: 'Muito insatisfeito',
  sentiment_very_satisfied: 'Muito satisfeito',
  sentiment_worried: 'Preocupado',
  set_meal: 'Refeição',
  settings_accessibility: 'Acessibilidade',
  settings_applications: 'Aplicações',
  settings_backup_restore: 'Backup',
  settings_bluetooth: 'Bluetooth',
  settings_brightness: 'Brilho',
  settings_cell: 'Celular',
  settings_ethernet: 'Ethernet',
  settings_input_antenna: 'Antena',
  settings_input_component: 'Componente',
  settings_input_composite: 'Compósito',
  settings_input_hdmi: 'HDMI',
  settings_input_svideo: 'S-Video',
  settings_overscan: 'Overscan',
  settings_phone: 'Telefone',
  settings_power: 'Energia',
  settings_remote: 'Controle remoto',
  settings_voice: 'Voz',
  settings_outlined: 'Configurações',
  shapes: 'Formas',
  share_arrival_time: 'Horário de chegada',
  share_location: 'Compartilhar local',
  share_outlined: 'Compartilhar',
  shield_outlined: 'Proteção',
  shopping_bag: 'Sacola',
  shopping_basket: 'Cesta',
  shopping_cart_outlined: 'Carrinho',
  short_text: 'Texto curto',
  shortcut: 'Atalho',
  shower: 'Chuveiro',
  shuffle_on: 'Aleatório ligado',
  shutter_speed: 'Velocidade do obturador',
  sick: 'Doente',
  sign_language_outlined: 'Libras',
  signpost: 'Placa',
  sim_card: 'Cartão SIM',
  sim_card_alert: 'Cartão SIM',
  sim_card_download: 'Baixar SIM',
  single_bed: 'Cama de solteiro',
  sip: 'SIP',
  skateboarding_outlined: 'Skate',
  skip_next_outlined: 'Próximo',
  skip_previous_outlined: 'Anterior',
  sliding: 'Deslizar',
  smart_button: 'Botão inteligente',
  smart_display: 'Display inteligente',
  smart_outlet: 'Tomada inteligente',
  smart_screen: 'Tela inteligente',
  smart_toy: 'Brinquedo inteligente',
  smartphone_outlined: 'Celular',
  smoke_free: 'Proibido fumar',
  smoking_rooms: 'Fumar permitido',
  sms_failed: 'Mensagem falhou',
  sms_outlined: 'Mensagem',
  snippet_folder: 'Pasta',
  soap: 'Sabão',
  social_distance: 'Distância social',
  south: 'Sul',
  south_america: 'América do Sul',
  south_east: 'Sudeste',
  south_west: 'Sudoeste',
  space_bar: 'Espaço',
  space_dashboard: 'Painel espacial',
  spatial_audio: 'Áudio espacial',
  spatial_audio_off: 'Áudio espacial off',
  spatial_tracking: 'Rastreamento espacial',
  speaker: 'Alto-falante',
  speaker_group: 'Grupo de alto-falantes',
  speaker_notes: 'Notas do alto-falante',
  speaker_notes_off: 'Sem notas',
  speaker_phone: 'Viva-voz',
  speed: 'Velocidade',
  spellcheck: 'Correção ortográfica',
  split_screen: 'Dividir tela',
  sports_baseball: 'Beisebol',
  sports_bar_outlined: 'Bar',
  sports_basketball_outlined: 'Basquete',
  sports_cricket_outlined: 'Críquete',
  sports_esports_outlined: 'Games',
  sports_football: 'Futebol',
  sports_golf_outlined: 'Golfe',
  sports_gymnastics: 'Ginástica',
  sports_handball: 'Handebol',
  sports_hockey_outlined: 'Hóquei',
  sports_kabaddi: 'Kabaddi',
  sports_martial_arts: 'Artes marciais',
  sports_mma_outlined: 'MMA',
  sports_motorsports_outlined: 'Motoresportes',
  sports_rugby_outlined: 'Rúgbi',
  sports_score: 'Placar',
  sports_soccer_outlined: 'Futebol',
  sports_tennis_outlined: 'Tênis',
  sports_volleyball_outlined: 'Vôlei',
  sprinkler: 'Aspersor',
  stairs: 'Escadas',
  star_outline: 'Favoritar',
  stars: 'Estrelas',
  start: 'Iniciar',
  stay_current_landscape: 'Paisagem',
  stay_current_portrait: 'Retrato',
  stay_primary_landscape: 'Paisagem',
  stay_primary_portrait: 'Retrato',
  sticky_note_2_outlined: 'Anotações',
  stop_circle: 'Parar',
  stop_screen_share: 'Parar compartilhamento',
  storage: 'Armazenamento',
  store: 'Loja',
  storefront_outlined: 'Loja',
  storm_outlined: 'Tempestade',
  straight: 'Reta',
  straighten_outlined: 'Endireitar',
  streaming: 'Streaming',
  streetview_outlined: 'Vista da rua',
  strikethrough_s: 'Riscado',
  style: 'Estilo',
  styler: 'Estilo',
  subdirectory_arrow_left: 'Subdiretório',
  subdirectory_arrow_right: 'Subdiretório',
  subject: 'Assunto',
  subscript: 'Subscrito',
  subtitle: 'Legenda',
  subtract: 'Subtrair',
  superscript: 'Sobrescrito',
  support: 'Suporte',
  support_agent: 'Suporte',
  surveillance_camera: 'Câmera de vigilância',
  swap_calls: 'Trocar chamadas',
  swipe: 'Deslizar',
  swipe_down: 'Deslizar para baixo',
  swipe_down_alt: 'Deslizar para baixo',
  swipe_left: 'Deslizar para esquerda',
  swipe_left_alt: 'Deslizar para esquerda',
  swipe_right: 'Deslizar para direita',
  swipe_right_alt: 'Deslizar para direita',
  swipe_up: 'Deslizar para cima',
  swipe_up_alt: 'Deslizar para cima',
  swipe_vertical: 'Deslizar vertical',
  switch_access_shortcut: 'Atalho',
  switch_access_shortcut_add: 'Adicionar atalho',
  switch_account: 'Trocar conta',
  switch_camera: 'Trocar câmera',
  switch_left: 'Esquerda',
  switch_right: 'Direita',
  switch_video: 'Trocar vídeo',
  synagogue: 'Sinagoga',
  sync_disabled: 'Sincronização desabilitada',
  sync_lock: 'Sincronização bloqueada',
  sync_problem: 'Problema de sincronização',
  system_security_update: 'Atualização',
  system_security_update_good: 'Atualização',
  system_security_update_warning: 'Atualização',
  system_update: 'Atualização',
  system_update_alt: 'Atualização',
  tab: 'Aba',
  tab_unselected: 'Aba não selecionada',
  table_bar: 'Bar',
  table_restaurant: 'Mesa',
  tablet_mac: 'Tablet',
  tablet_android: 'Tablet',
  takeout_dining: 'Delivery',
  tapas: 'Tapas',
  task: 'Tarefa',
  task_alt: 'Tarefa',
  taxi_alert: 'Taxi',
  temple_buddhist: 'Templo',
  temple_hindu: 'Templo',
  terminal: 'Terminal',
  text_rotate_up: 'Rotacionar texto',
  text_rotate_vertical: 'Rotacionar texto',
  text_rotation_angledown: 'Rotacionar texto',
  text_rotation_angleup: 'Rotacionar texto',
  text_rotation_down: 'Rotacionar texto',
  text_rotation_none: 'Sem rotação',
  text_snippet: 'Trecho',
  textsms: 'Mensagem',
  theater_comedy_outlined: 'Teatro',
  thermostat: 'Termostato',
  thermostat_auto: 'Termostato auto',
  thermostat_carbon: 'Carbono',
  thumb_down_alt: 'Não curtir',
  thumb_down_off_alt: 'Não curtir',
  thumb_up_alt: 'Curtir',
  thumb_up_off_alt: 'Curtir',
  thumbs_up_down: 'Avaliação',
  thunderstorm_outlined: 'Tempestade',
  ticket: 'Ingresso',
  ticket_outlined: 'Ingresso',
  timer_10: 'Temporizador 10',
  timer_10_select: 'Temporizador 10',
  timer_3: 'Temporizador 3',
  timer_3_select: 'Temporizador 3',
  timer_outlined: 'Temporizador',
  timelapse: 'Lapso de tempo',
  time_to_leave: 'Hora de sair',
  tips_and_updates_outlined: 'Dicas',
  tissue: 'Lenço',
  to_top: 'Ir para o topo',
  today: 'Hoje',
  token: 'Token',
  toll: 'Pedágio',
  tonality: 'Tonalidade',
  topic: 'Tópico',
  tornado_outlined: 'Tornado',
  total_dissatisfaction: 'Insatisfação',
  tour: 'Tour',
  toy_brush: 'Brinquedo',
  toy_fan: 'Ventilador',
  train_outlined: 'Trem',
  tram_outlined: 'Bonde',
  transparent: 'Transparente',
  travel: 'Viagem',
  trending_down_outlined: 'Declínio',
  trending_flat: 'Estável',
  trending_up_outlined: 'Evolução',
  trip_origin: 'Origem',
  trolley: 'Carrinho',
  try: 'Tentar',
  tsunami_outlined: 'Tsunami',
  tty: 'TTY',
  tune: 'Ajustar',
  tungsten: 'Tungstênio',
  turn_left: 'Virar à esquerda',
  turn_right: 'Virar à direita',
  turn_sharp_left: 'Virar bruscamente à esquerda',
  turn_sharp_right: 'Virar bruscamente à direita',
  turn_slight_left: 'Virar levemente à esquerda',
  turn_slight_right: 'Virar levemente à direita',
  tv_off: 'TV desligada',
  two_wheeler_outlined: 'Moto',
  type_specimen: 'Espécime',
  u_turn_left: 'Retorno à esquerda',
  u_turn_right: 'Retorno à direita',
  umbrella: 'Guarda-chuva',
  unarchive: 'Desarquivar',
  undo: 'Desfazer',
  unfold_more_outlined: 'Expandir',
  ungroup: 'Desagrupar',
  uninstall: 'Desinstalar',
  unpin: 'Desfixar',
  unpublish: 'Despublicar',
  unpaid: 'Não pago',
  update_disabled: 'Atualização desabilitada',
  update_outlined: 'Atualizar',
  upgrade: 'Atualizar',
  upload_outlined: 'Enviar',
  usb: 'USB',
  usb_off: 'USB off',
  vaccines: 'Vacinas',
  vape_free: 'Vape proibido',
  vaping_rooms: 'Vape permitido',
  verified_user_outlined: 'Usuário verificado',
  vertical_align_bottom: 'Alinhar embaixo',
  vertical_align_center: 'Centralizar vertical',
  vertical_align_top: 'Alinhar em cima',
  vertical_distribute: 'Distribuir vertical',
  vertical_split: 'Dividir vertical',
  vibration: 'Vibração',
  video_file: 'Arquivo de vídeo',
  video_label: 'Rótulo de vídeo',
  video_library_outlined: 'Vídeos',
  video_settings_outlined: 'Config. de vídeo',
  video_stable: 'Vídeo estável',
  videocam_off: 'Câmera desligada',
  videocam_outlined: 'Câmera',
  view_agenda_outlined: 'Agenda',
  view_carousel_outlined: 'Carrossel',
  view_column_outlined: 'Colunas',
  view_comfy: 'Confortável',
  view_comfy_alt: 'Confortável',
  view_compact: 'Compacto',
  view_compact_alt: 'Compacto',
  view_cozy: 'Aconchegante',
  view_day_outlined: 'Dia',
  view_in_ar: 'AR',
  view_in_ar_new: 'AR',
  view_kanban: 'Kanban',
  view_list_outlined: 'Lista',
  view_module_outlined: 'Módulos',
  view_quilt_outlined: 'Blocos',
  view_sidebar_outlined: 'Lateral',
  view_stream_outlined: 'Contínuo',
  view_timeline: 'Linha do tempo',
  view_week_outlined: 'Semana',
  vignette: 'Vinheta',
  villa: 'Villa',
  visibility_off: 'Ocultar',
  visibility_outlined: 'Visualizar',
  voice_chat: 'Chat de voz',
  voice_over_off: 'Voz off',
  voicemail: 'Correio de voz',
  volume_down: 'Volume baixo',
  volume_mute: 'Mudo',
  volume_off: 'Mudo',
  volume_up_outlined: 'Volume',
  volunteer_activism: 'Voluntariado',
  vpn_key_outlined: 'Chave',
  vpn_lock: 'VPN bloqueada',
  wallpaper: 'Papel de parede',
  wallpaper_outlined: 'Papel de parede',
  warehouse_outlined: 'Depósito',
  warning_amber: 'Atenção',
  watch: 'Relógio',
  watch_later: 'Ver depois',
  watch_off: 'Relógio off',
  water_damage: 'Dano de água',
  water_drop_outlined: 'Água',
  waterfall_chart: 'Gráfico em cascata',
  waves_outlined: 'Ondas',
  waving_hand: 'Acenando',
  wb_auto_outlined: 'Balanço automático',
  wb_cloudy_outlined: 'Nublado',
  wb_incandescent_outlined: 'Lâmpada',
  wb_iridescent_outlined: 'Brilho',
  wb_shade_outlined: 'Sombra',
  wb_twilight_outlined: 'Crepúsculo',
  web: 'Web',
  web_asset: 'Recurso web',
  web_asset_off: 'Recurso web off',
  webhook: 'Webhook',
  weekend_outlined: 'Fim de semana',
  west: 'Oeste',
  whatshot: 'Tendência',
  wheelchair_pickup_outlined: 'Cadeira de rodas',
  where_to_vote: 'Onde votar',
  widgets: 'Widgets',
  width: 'Largura',
  width_full: 'Largura total',
  width_normal: 'Largura normal',
  width_wide: 'Largura ampla',
  wifi_1_bar: 'Wi-Fi fraco',
  wifi_2_bar: 'Wi-Fi médio',
  wifi_calling: 'Chamada Wi-Fi',
  wifi_calling_1: 'Chamada Wi-Fi',
  wifi_calling_2: 'Chamada Wi-Fi',
  wifi_calling_3: 'Chamada Wi-Fi',
  wifi_channel: 'Canal Wi-Fi',
  wifi_find: 'Encontrar Wi-Fi',
  wifi_lock: 'Wi-Fi bloqueado',
  wifi_off: 'Wi-Fi desligado',
  wifi_password: 'Senha Wi-Fi',
  wifi_protected_setup: 'WPS',
  wifi_tethering: 'Roteamento',
  wifi_tethering_error: 'Erro de roteamento',
  wifi_tethering_off: 'Roteamento off',
  wind_power_outlined: 'Energia eólica',
  window: 'Janela',
  wine_bar: 'Bar de vinhos',
  work: 'Trabalho',
  work_history: 'Histórico de trabalho',
  work_off: 'Trabalho off',
  work_outline: 'Trabalho',
  workspace_premium_outlined: 'Premium',
  workspaces: 'Espaços de trabalho',
  wrap_text: 'Quebra de texto',
  wrong_location: 'Local errado',
  wysiwyg: 'WYSIWYG',
  yard: 'Quintal',
  your_trips: 'Suas viagens',
  youtube_searched_for: 'Youtube',
  zoom_in_map: 'Ampliar mapa',
  zoom_in_outlined: 'Ampliar',
  zoom_out_map: 'Reduzir mapa',
  zoom_out_outlined: 'Reduzir',
  zoom_out_outlined_outlined: 'Reduzir',
};

function getIconLabel(iconName: string): string {
  if (ICON_LABELS[iconName]) return ICON_LABELS[iconName];
  return iconName.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  template: `<router-outlet />`,
})
export class AppComponent implements AfterViewInit, OnDestroy {
  private tooltip: HTMLDivElement | null = null;
  private currentIcon: HTMLElement | null = null;
  private destroyFns: (() => void)[] = [];

  ngAfterViewInit() {
    this.createTooltip();
    this.setupListeners();
  }

  ngOnDestroy() {
    this.destroyFns.forEach(fn => fn());
    this.tooltip?.remove();
  }

  private createTooltip() {
    this.tooltip = document.createElement('div');
    this.tooltip.className = 'icon-tooltip';
    document.body.appendChild(this.tooltip);
  }

  private setupListeners() {
    const onMouseOver = (e: MouseEvent) => {
      const target = e.target as HTMLElement;
      const icon = target.closest('.material-icons');
      if (!icon || !this.tooltip) return;

      const iconName = icon.textContent?.trim() || '';
      if (!iconName || /^[0-9]+$/.test(iconName)) return;

      this.currentIcon = icon as HTMLElement;
      this.tooltip.textContent = getIconLabel(iconName);
      this.tooltip.style.opacity = '1';
      this.positionTooltip(e);
    };

    const onMouseMove = (e: MouseEvent) => {
      if (this.currentIcon) this.positionTooltip(e);
    };

    const onMouseOut = (e: MouseEvent) => {
      const target = e.target as HTMLElement;
      const icon = target.closest('.material-icons');
      if (icon === this.currentIcon || !icon) {
        this.currentIcon = null;
        if (this.tooltip) this.tooltip.style.opacity = '0';
      }
    };

    document.addEventListener('mouseover', onMouseOver);
    document.addEventListener('mousemove', onMouseMove);
    document.addEventListener('mouseout', onMouseOut);
    this.destroyFns.push(
      () => document.removeEventListener('mouseover', onMouseOver),
      () => document.removeEventListener('mousemove', onMouseMove),
      () => document.removeEventListener('mouseout', onMouseOut)
    );
  }

  private positionTooltip(e: MouseEvent) {
    if (!this.tooltip) return;
    const offset = 10;
    const tipWidth = this.tooltip.offsetWidth;
    const tipHeight = this.tooltip.offsetHeight;
    let x = e.clientX + offset;
    let y = e.clientY + offset;
    if (x + tipWidth > window.innerWidth - 4) x = e.clientX - tipWidth - offset;
    if (y + tipHeight > window.innerHeight - 4) y = e.clientY - tipHeight - offset;
    this.tooltip.style.left = `${x}px`;
    this.tooltip.style.top = `${y}px`;
  }
}
